/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p24;

import javax.swing.JOptionPane;

/**
 *
 * @author 18PROGB0133
 */
public class FrmConverciones extends javax.swing.JFrame {

    private int Gramos;

    /**
     * Creates new form FrmConverciones
     */
    public FrmConverciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAconvertir = new javax.swing.JLabel();
        txtMetros = new javax.swing.JTextField();
        lblMetros = new javax.swing.JLabel();
        rbCentimetros = new javax.swing.JRadioButton();
        rbMilimetros = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtResultadoMetros = new javax.swing.JTextField();
        lblHoras = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        rbMinutos = new javax.swing.JRadioButton();
        rbSegundos = new javax.swing.JRadioButton();
        txtResultadoHoras = new javax.swing.JTextField();
        lblKG = new javax.swing.JLabel();
        lblResultadoHoras = new javax.swing.JLabel();
        btnConvierte = new javax.swing.JButton();
        lblResultadoMetros = new javax.swing.JLabel();
        txtGramos = new javax.swing.JTextField();
        txtKG = new javax.swing.JTextField();
        rbDerecha = new javax.swing.JRadioButton();
        rbIzquierda = new javax.swing.JRadioButton();
        lblGramos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("     CONVERCIONES   P24");

        lblAconvertir.setText("A convertir");

        lblMetros.setText("Metros");

        rbCentimetros.setText("Centimetros");
        rbCentimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentimetrosActionPerformed(evt);
            }
        });

        rbMilimetros.setText("Milimetros");
        rbMilimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMilimetrosActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultado");

        lblHoras.setText("Horas");

        rbMinutos.setText("Minutos");
        rbMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMinutosActionPerformed(evt);
            }
        });

        rbSegundos.setText("Segundos");
        rbSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSegundosActionPerformed(evt);
            }
        });

        lblKG.setText("KG");

        lblResultadoHoras.setText("Resultado");

        btnConvierte.setText("Convierte");
        btnConvierte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvierteActionPerformed(evt);
            }
        });

        lblResultadoMetros.setText("Resultado");

        rbDerecha.setText("------>");
        rbDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDerechaActionPerformed(evt);
            }
        });

        rbIzquierda.setText("<------");
        rbIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIzquierdaActionPerformed(evt);
            }
        });

        lblGramos.setText("Gramos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblHoras)))
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKG, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(txtHoras)
                    .addComponent(txtMetros)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMetros))
                            .addComponent(lblAconvertir))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCentimetros)
                            .addComponent(rbIzquierda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblResultadoMetros)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMinutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResultadoHoras)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSegundos)
                            .addComponent(rbDerecha)
                            .addComponent(rbMilimetros))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtResultadoMetros)
                                .addGap(8, 8, 8))
                            .addComponent(txtGramos)
                            .addComponent(txtResultadoHoras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvierte)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblKG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGramos)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAconvertir)
                    .addComponent(rbCentimetros)
                    .addComponent(lblResultadoMetros))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMetros)
                        .addGap(8, 8, 8)
                        .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblHoras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMilimetros)
                            .addComponent(txtResultadoMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMinutos)
                            .addComponent(lblResultadoHoras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSegundos)
                    .addComponent(txtResultadoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKG)
                    .addComponent(lblGramos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGramos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDerecha)
                    .addComponent(txtKG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvierte)
                    .addComponent(rbIzquierda))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCentimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentimetrosActionPerformed
        rbCentimetros.setSelected(true);
        rbMilimetros.setSelected(false);
        try{
        double centimetros= Double.parseDouble(txtMetros.getText());
        txtResultadoMetros.setText(String.valueOf(centimetros*100));
        txtMetros.setText("");
        } catch (Exception sh){
            JOptionPane.showMessageDialog(null,"ERROR DEBES ESCRIBIR UN VALOR!");
        }
    }//GEN-LAST:event_rbCentimetrosActionPerformed

    private void rbMilimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMilimetrosActionPerformed
        rbCentimetros.setSelected(false);
        rbMilimetros.setSelected(true);
        try{
            double milimetros = Double.parseDouble(txtMetros.getText());
            txtResultadoMetros.setText(String.valueOf(milimetros*1000));
            txtMetros.setText("");
        }catch (Exception sh){
            JOptionPane.showMessageDialog(null,"ERROR DEBES ESCRIBIR UN VALOR!");
        }
    }//GEN-LAST:event_rbMilimetrosActionPerformed

    private void rbMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMinutosActionPerformed
       rbMinutos.setSelected(true);
       rbSegundos.setSelected(false);
       try{
           double minutos = Double.parseDouble(txtHoras.getText());
           txtResultadoHoras.setText(String.valueOf(minutos*60));
           txtHoras.setText("");
            }catch (Exception sh){
            JOptionPane.showMessageDialog(null,"ERROR DEBES ESCRIBIR UN VALOR!");
       }
    }//GEN-LAST:event_rbMinutosActionPerformed

    private void rbSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSegundosActionPerformed
        rbMinutos.setSelected(false);
       rbSegundos.setSelected(true);
       try{
           double segundos = Double.parseDouble(txtHoras.getText());
           txtResultadoHoras.setText(String.valueOf(segundos*3600));
           txtHoras.setText("");
       }catch(Exception sh){
           JOptionPane.showMessageDialog(null,"ERROR DEBES ESCRIBIR UN VALOR!");
       }
    }//GEN-LAST:event_rbSegundosActionPerformed

    private void rbDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDerechaActionPerformed
        rbDerecha.setSelected(true);
        rbIzquierda.setSelected(false); 
        txtGramos.setEnabled(false);
        txtKG.setEnabled(true);
    }//GEN-LAST:event_rbDerechaActionPerformed

    private void rbIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIzquierdaActionPerformed
       rbDerecha.setSelected(false);
        rbIzquierda.setSelected(true);
        txtKG.setEnabled(false);
        txtGramos.setEnabled(true);
    }//GEN-LAST:event_rbIzquierdaActionPerformed

    private void btnConvierteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvierteActionPerformed
       if(rbDerecha.isSelected()){  
      rbDerecha.setEnabled(true);
      try{
          double KG = Double.parseDouble(txtGramos.getText());
          txtGramos.setText(String.valueOf(Gramos/1000));
          txtGramos.setText("");
          
      }
    }//GEN-LAST:event_btnConvierteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConverciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConverciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConverciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConverciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConverciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnConvierte;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel lblAconvertir;
    javax.swing.JLabel lblGramos;
    javax.swing.JLabel lblHoras;
    javax.swing.JLabel lblKG;
    javax.swing.JLabel lblMetros;
    javax.swing.JLabel lblResultadoHoras;
    javax.swing.JLabel lblResultadoMetros;
    javax.swing.JRadioButton rbCentimetros;
    javax.swing.JRadioButton rbDerecha;
    javax.swing.JRadioButton rbIzquierda;
    javax.swing.JRadioButton rbMilimetros;
    javax.swing.JRadioButton rbMinutos;
    javax.swing.JRadioButton rbSegundos;
    javax.swing.JTextField txtGramos;
    javax.swing.JTextField txtHoras;
    javax.swing.JTextField txtKG;
    javax.swing.JTextField txtMetros;
    javax.swing.JTextField txtResultadoHoras;
    javax.swing.JTextField txtResultadoMetros;
    // End of variables declaration//GEN-END:variables
}
